### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by albaropereyra22** [arslan2012/drogon-realworld-example-app#3]
Hello,

I am unable to compile,

I got the following error when I tried to compile it.

![image](https://github.com/user-attachments/assets/5c9d7d9a-3e56-48cb-a569-59a796c9d86e)

Please advise,
Albaro,

**Comment by arslan2012** [comment]
[Turns out someone already found the issue](https://github.com/arslan2012/drogon-realworld-example-app/issues/1), anyway, code updated!
